server:
  port: 8080
spring:
  application:
    name: customer
  datasource:
    username: 'malarcondev'
    url: jdbc:postgresql://localhost:5432/customer
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    fetch-registry: true
    register-with-eureka: true